const roles={
Owner:{modules:["Live Sales","Profit & Expenses","Inventory Alerts","Employee Performance","Daily Reports"],center:"BUSINESS PULSE",summary:"₱48,650 Today",metrics:[["Sales","₱48,650"],["Profit","₱16,240"],["Alerts","3"]]},
Manager:{modules:["Operations","Staff Scheduling","Inventory","Purchase Orders","Approvals","Reports"],center:"OPERATIONS LIVE",summary:"2 approvals pending",metrics:[["On Shift","8"],["Low Stock","4"],["POs","2"]]},
Cashier:{modules:["POS","Orders","Payments","Discounts","Returns","Shift Reconciliation"],center:"CURRENT SHIFT",summary:"Terminal 01 • Open",metrics:[["Orders","37"],["Sales","₱21,840"],["Returns","1"]]},
Staff:{modules:["Tasks","Attendance","Orders","Stock Requests","Notifications"],center:"MY SHIFT",summary:"Clocked in • 8:03 AM",metrics:[["Tasks","6"],["Done","3"],["Alerts","2"]]}
};const app=document.querySelector("#app");
function home(){app.innerHTML='<div class="shell"><section class="card"><div class="brand"><small>SMART OPERATIONS • ONE COMMAND CENTER</small><h1>SME Business Command Center</h1><p>Select your portal. Each role has its own independent workspace.</p></div><div class="roles">'+Object.entries(roles).map(([r,d])=>'<button class="role" data-role="'+r+'"><b>'+r.toUpperCase()+'</b><span>'+d.modules.join(" • ")+'</span></button>').join("")+'</div></section></div>';document.querySelectorAll("[data-role]").forEach(b=>b.onclick=()=>portal(b.dataset.role))}
function portal(role){let d=roles[role];app.innerHTML='<div class="shell"><section class="card"><div class="top"><div><small>SME COMMAND CENTER</small><h2>'+role+' Portal</h2></div><button class="back">← Switch Role</button></div><div class="orbit"><div class="center"><div><strong>'+d.center+'</strong><br><span>'+d.summary+'</span></div></div>'+d.modules.map((m,i)=>'<button class="module" data-m="'+m+'" style="'+pos(i,d.modules.length)+'">'+m+'</button>').join("")+'</div><div class="panel"><h3>Overview</h3>'+d.metrics.map(x=>'<span class="metric">'+x[0]+'<b>'+x[1]+'</b></span>').join("")+'<p>Select any orbit module to open its workspace.</p></div></section></div>';document.querySelector(".back").onclick=home;document.querySelectorAll(".module").forEach(b=>b.onclick=()=>openModule(role,b))}
function pos(i,n){let a=(i/n)*Math.PI*2-Math.PI/2,r=40,x=50+r*Math.cos(a),y=50+r*Math.sin(a);return 'left:calc('+x+'% - 77px);top:calc('+y+'% - 28px)'}
function openModule(role,b){document.querySelectorAll(".module").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelector(".panel").innerHTML='<h3>'+b.dataset.m+'</h3><p><b>'+role+' workspace</b></p><p>This module is connected to the '+role+' portal and ready for the next functional layer.</p><button class="back" onclick="portal(\''+role+'\')">Back to overview</button>'}home();