const roles={
Owner:{modules:["Live Sales","Profit & Expenses","Inventory","People","Approvals","Cash & Bank","Suppliers & Purchasing","Reports","Notification Center"],center:"BUSINESS PULSE",summary:"₱48,650 Today",metrics:[["Sales","₱48,650"],["Profit","₱16,240"],["Alerts","3"]]},
Manager:{modules:["Operations","Staff Scheduling","Inventory","Purchase Orders","Approvals","Reports"],center:"OPERATIONS LIVE",summary:"2 approvals pending",metrics:[["On Shift","8"],["Low Stock","4"],["POs","2"]]},
Cashier:{modules:["POS","Orders","Payments","Discounts","Returns","Shift Reconciliation"],center:"CURRENT SHIFT",summary:"Terminal 01 • Open",metrics:[["Orders","37"],["Sales","₱21,840"],["Returns","1"]]},
Staff:{modules:["Tasks","Attendance","Orders","Stock Requests","Notifications"],center:"MY SHIFT",summary:"Clocked in • 8:03 AM",metrics:[["Tasks","6"],["Done","3"],["Alerts","2"]]}
};const app=document.querySelector("#app");
const DEFAULT_STATE={sales:48650,expenses:12410,profit:17040,cash:18450,alerts:3,lastExpense:null};
function loadState(){try{return Object.assign({},DEFAULT_STATE,JSON.parse(localStorage.getItem("smeState")||"{}"))}catch(e){return {...DEFAULT_STATE}}}
function saveState(st){localStorage.setItem("smeState",JSON.stringify(st))}
function money(n){return "₱"+Number(n||0).toLocaleString()}

function home(){const entries=Object.entries(roles);app.innerHTML='<div class="shell"><section class="card orbit-first"><div class="orbit role-orbit"><div class="center"><div><strong>COMMAND<br>CENTER</strong><br><span>Choose a role</span></div></div>'+entries.map(([r,d],i)=>'<button class="module role-node" data-role="'+r+'" style="'+pos(i,entries.length)+'">'+r.toUpperCase()+'</button>').join("")+'</div><div class="orbit-caption"><small>SME BUSINESS COMMAND CENTER</small><h1>Choose Your Portal</h1></div></section></div>';document.querySelectorAll("[data-role]").forEach(b=>b.onclick=()=>portal(b.dataset.role))}
function portal(role){let d=roles[role],st=loadState();if(role==="Owner"){d={...d,summary:money(st.sales)+" Today"}}app.innerHTML='<div class="shell"><section class="card portal-orbit-only"><button class="back floating-back">← Roles</button><div class="portal-label"><small>SME COMMAND CENTER</small><h2>'+role+' Portal</h2></div><div class="orbit"><button class="center center-action" id="orbitCenter" type="button"><div><strong>'+d.center+'</strong><br><span>'+d.summary+'</span><em>Tap for snapshot</em></div></button>'+d.modules.map((m,i)=>'<button class="module'+(role==="Owner"&&m==="Notification Center"?' new-feature':'')+'" data-m="'+m+'" style="'+pos(i,d.modules.length)+'">'+m+(role==="Owner"&&m==="Notification Center"?'<span class="new-badge">★ NEW</span>':'')+'</button>').join("")+'</div></section></div>';document.querySelector(".back").onclick=home;document.querySelector("#orbitCenter").onclick=()=>openPulse(role);document.querySelectorAll(".module").forEach(b=>b.onclick=()=>openModule(role,b))}
function pos(i,n){let a=(i/n)*Math.PI*2-Math.PI/2,r=41,x=50+r*Math.cos(a),y=50+r*Math.sin(a);return 'left:'+x+'%;top:'+y+'%;transform:translate(-50%,-50%)'}
const ownerViews={
"Live Sales":'<div class="demo-grid"><div><small>TODAY</small><b>₱48,650</b></div><div><small>TRANSACTIONS</small><b>126</b></div><div><small>AVG ORDER</small><b>₱386</b></div></div><p>Recent: #0126 ₱650 • #0125 ₱420 • #0124 ₱1,080</p>',
"Profit & Expenses":'<div class="demo-grid"><div><small>REVENUE</small><b>₱48,650</b></div><div><small>EXPENSES</small><b>₱12,410</b></div><div><small>EST. PROFIT</small><b>₱17,040</b></div></div><button class="action">+ Add Expense</button>',
"Inventory":'<div class="demo-grid"><div><small>PRODUCTS</small><b>186</b></div><div><small>LOW STOCK</small><b>3</b></div><div><small>OUT</small><b>1</b></div></div><p>Milk 4 left • Cups 12 left • Syrup 2 left</p>',
"People":'<div class="demo-grid"><div><small>ON SHIFT</small><b>8</b></div><div><small>ABSENT</small><b>2</b></div><div><small>ATTENDANCE</small><b>96%</b></div></div><p>Top today: Donna • 31 completed tasks</p>',
"Approvals":'<div class="request"><b>Refund #1048 — ₱1,250</b><br><button class="action">Approve</button> <button class="action">Reject</button></div><div class="request"><b>Purchase Request — ₱8,500</b><br><button class="action">Approve</button> <button class="action">Reject</button></div>',
"Cash & Bank":'<div class="demo-grid"><div><small>CASH</small><b>₱18,450</b></div><div><small>GCASH</small><b>₱12,800</b></div><div><small>CARD</small><b>₱17,400</b></div></div><p>Expected ₱18,450 • Actual ₱18,450 • Variance ₱0</p><button class="action">Reconcile Shift</button>',
"Suppliers & Purchasing":'<div class="demo-grid"><div><small>SUPPLIERS</small><b>12</b></div><div><small>OPEN PO</small><b>3</b></div><div><small>PAYABLE</small><b>₱24,600</b></div></div><p>2 deliveries arriving today</p><button class="action">+ Create PO</button>',
"Reports":'<div class="report-modules"><button class="report-module" type="button"><b>Daily Sales</b><span>₱48,650 • 126 transactions</span></button><button class="report-module" type="button"><b>Cash Flow</b><span>In ₱48,650 • Out ₱12,410 • Net ₱36,240</span></button><button class="report-module" type="button"><b>Profit & Loss</b><span>Revenue • COGS • Expenses • Net Profit</span></button><button class="report-module" type="button"><b>Inventory Movement</b><span>Stock In • Stock Out • Adjustments</span></button><button class="report-module" type="button"><b>Expenses</b><span>Today ₱12,410</span></button><button class="report-module" type="button"><b>Exceptions</b><span>2 items need review</span></button></div><a class="action export-link" href="?screen=pdf">Export PDF</a> <a class="action export-link" href="?screen=excel">Export Excel</a>',
"Notification Center":'<div class="alerts-list"><button class="alert-item urgent" data-target="Inventory"><b>Low Stock</b><span>3 products need attention</span></button><button class="alert-item" data-target="Approvals"><b>Approval Required</b><span>2 requests are waiting</span></button><button class="alert-item" data-target="Cash & Bank"><b>Cash Check</b><span>Review today’s reconciliation</span></button><button class="alert-item" data-target="Suppliers & Purchasing"><b>Supplier Delivery</b><span>2 deliveries arriving today</span></button><button class="alert-item" data-target="Profit & Expenses"><b>Expense Activity</b><span>View the latest recorded expense</span></button></div><p class="alert-hint">Tap an alert to open its workspace.</p>'
